name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  # Use for multi-branch deployment
  APP_ENV: ${{ github.head_ref || github.ref_name }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  REPO_NAME: ${{ github.repository }}

jobs:

  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOYMENT_VPS_HOST }}
          username: ${{ secrets.DEPLOYMENT_VPS_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_VPS_SSH_KEY }}
          port: ${{ secrets.DEPLOYMENT_VPS_PORT }}
          timeout: 180s
          script: |
            echo "Connected to VPS successfully!"
            cd ~ && mkdir -p deploy-docker
            cd deploy-docker
            wget https://raw.githubusercontent.com/${{ env.REPO_NAME }}/main/docker-compose.yaml -O ~/deploy-docker/docker-compose.yaml
            docker-compose pull --include-deps
            docker-compose up -d
            echo "Deployed to VPS successfully!"
