name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "staging", "main" ]

jobs:
  build-and-push:
    name: Build and Publish MlFlow image
    uses: ./.github/workflows/mflow-publish.yml
    secrets: inherit

  deploy-apps:
    name: Deploy docker network to VPS server
    needs: build-and-push
    uses: ./.github/workflows/compose-deploy.yml
    secrets: inherit
