name: Docs2Pages

on:
  push:

jobs:
  build-docs:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout the docs branch
        run: |
          git fetch origin documentation  # Fetches the docs branch
          git checkout documentation  # Switches to the docs branch

      - name: Clone Other Repositories
        run: |
          rm -rf repos
          git clone https://github.com/fhswf-study-projects/mlops-data-processor repos/mlops-data-processor
          git clone https://github.com/fhswf-study-projects/mlops-pipeline-api repos/mlops-pipeline-api
          git clone https://github.com/fhswf-study-projects/mlops-streamlit-ui repos/mlops-streamlit-ui       

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies & Build Docs
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install sphinx-copybutton
          cd docs
          sphinx-apidoc -o streamlit-ui -H Streamlit-UI ../repos/mlops-streamlit-ui/app
          sphinx-apidoc -o data-processor -H Data-Processor ../repos/mlops-data-processor/app
          sphinx-apidoc -o pipeline-api -H Pipeline-API ../repos/mlops-pipeline-api/app
          sphinx-build -b html . _build/html
          mkdir -p gh-pages
          touch gh-pages/.nojekyll
          cd .. 
          cp -r docs/_build/html/* gh-pages/

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: gh-pages